#ifndef _ACTIVITYCOORDINATORTYPES_H
#define _ACTIVITYCOORDINATORTYPES_H

/* ActivityCoordinator API type definitions */

#if __POCC__ >= 500
#pragma once
#endif

typedef enum _ACTIVITY_COORDINATOR_RESOURCE {
    ACTIVITY_COORDINATOR_RESOURCE_USER_IDLE,
    ACTIVITY_COORDINATOR_RESOURCE_POWER,
    ACTIVITY_COORDINATOR_RESOURCE_NETWORK,
    ACTIVITY_COORDINATOR_RESOURCE_CPU,
    ACTIVITY_COORDINATOR_RESOURCE_MEMORY,
    ACTIVITY_COORDINATOR_RESOURCE_SYSTEM_DISK,
    ACTIVITY_COORDINATOR_RESOURCE_GPU
} ACTIVITY_COORDINATOR_RESOURCE;

typedef enum _ACTIVITY_COORDINATOR_CONDITION {
    ACTIVITY_COORDINATOR_CONDITION_GOOD,
    ACTIVITY_COORDINATOR_CONDITION_MEDIUM,
    ACTIVITY_COORDINATOR_CONDITION_NOT_SET
} ACTIVITY_COORDINATOR_CONDITION;

typedef enum _ACTIVITY_COORDINATOR_POLICY_TEMPLATE {
    ACTIVITY_COORDINATOR_POLICY_TEMPLATE_GOOD,
    ACTIVITY_COORDINATOR_POLICY_TEMPLATE_MEDIUM,
    ACTIVITY_COORDINATOR_POLICY_TEMPLATE_BASE,
    ACTIVITY_COORDINATOR_POLICY_TEMPLATE_EMPTY
} ACTIVITY_COORDINATOR_POLICY_TEMPLATE;

typedef enum _ACTIVITY_COORDINATOR_NOTIFICATION {
    ACTIVITY_COORDINATOR_NOTIFICATION_RUN,
    ACTIVITY_COORDINATOR_NOTIFICATION_STOP
} ACTIVITY_COORDINATOR_NOTIFICATION;

#ifndef __midl

DECLARE_HANDLE(ACTIVITY_COORDINATOR_SUBSCRIPTION);
DECLARE_HANDLE(ACTIVITY_COORDINATOR_POLICY);

typedef void (CALLBACK *ACTIVITY_COORDINATOR_CALLBACK)(
    ACTIVITY_COORDINATOR_NOTIFICATION notification,
    void *callbackContext
);

#endif /* !__midl */

#endif /* _ACTIVITYCOORDINATORTYPES_H */
