/* Generated from certexit.idl by POIDL version 0.80 - Do not edit */

#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif

#include <rpc.h>
#include <rpcndr.h>

#ifndef __RPCNDR_H_VERSION__
#error this stub requires an updated version of <rpcndr.h>
#endif /* __RPCNDR_H_VERSION__ */

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif /* COM_NO_WINDOWS_H */

#ifndef __certexit_h__
#define __certexit_h__

#if __POCC__ >= 500
#pragma once
#endif

/* Forward declarations */

#ifndef __ICertExit_FWD_DEFINED__
#define __ICertExit_FWD_DEFINED__
typedef interface ICertExit ICertExit;
#endif /* __ICertExit_FWD_DEFINED__ */

#ifndef __ICertExit2_FWD_DEFINED__
#define __ICertExit2_FWD_DEFINED__
typedef interface ICertExit2 ICertExit2;
#endif /* __ICertExit2_FWD_DEFINED__ */

/* Headers for imported files */

#include "wtypes.h"
#include "certmod.h"

#include "oaidl.h"


#include <winapifamily.h>

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)

#define EXITEVENT_INVALID               ( 0x0 )  // Invalid event
#define EXITEVENT_CERTISSUED            ( 0x1 )  // Certificate issued
#define EXITEVENT_CERTPENDING           ( 0x2 )  // Certificate pending
#define EXITEVENT_CERTDENIED            ( 0x4 )  // Certificate denied
#define EXITEVENT_CERTREVOKED           ( 0x8 )  // Certificate revoked
#define EXITEVENT_CERTRETRIEVEPENDING   ( 0x10 ) // Certificate retrieval
#define EXITEVENT_CRLISSUED             ( 0x20 ) // CRL issued
#define EXITEVENT_SHUTDOWN              ( 0x40 ) // Service shutdown
#define EXITEVENT_STARTUP               ( 0x80 ) // Service startup, fake event generated by exit module
#define EXITEVENT_CERTIMPORTED          ( 0x200 ) // Certificate Imported

/*****************************************************************************
 * ICertExit interface
 */
#ifndef __ICertExit_INTERFACE_DEFINED__
#define __ICertExit_INTERFACE_DEFINED__

EXTERN_C const IID IID_ICertExit;

#if defined(__cplusplus) && !defined(CINTERFACE)
#error no support for C++
#else /* C */
typedef struct ICertExitVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ICertExit *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ICertExit *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ICertExit *This);

    /*** IDispatch methods ***/
    HRESULT (STDMETHODCALLTYPE *GetTypeInfoCount)(
        ICertExit *This,
        UINT *pctinfo);

    HRESULT (STDMETHODCALLTYPE *GetTypeInfo)(
        ICertExit *This,
        UINT iTInfo,
        LCID lcid,
        ITypeInfo **ppTInfo);

    HRESULT (STDMETHODCALLTYPE *GetIDsOfNames)(
        ICertExit *This,
        REFIID riid,
        LPOLESTR *rgszNames,
        UINT cNames,
        LCID lcid,
        DISPID *rgDispId);

    HRESULT (STDMETHODCALLTYPE *Invoke)(
        ICertExit *This,
        DISPID dispIdMember,
        REFIID riid,
        LCID lcid,
        WORD wFlags,
        DISPPARAMS *pDispParams,
        VARIANT *pVarResult,
        EXCEPINFO *pExcepInfo,
        UINT *puArgErr);

    /*** ICertExit methods ***/
    HRESULT (STDMETHODCALLTYPE *Initialize)(
        ICertExit *This,
        const BSTR strConfig,
        LONG *pEventMask);

    HRESULT (STDMETHODCALLTYPE *Notify)(
        ICertExit *This,
        LONG ExitEvent,
        LONG Context);

    HRESULT (STDMETHODCALLTYPE *GetDescription)(
        ICertExit *This,
        BSTR *pstrDescription);

    END_INTERFACE
} ICertExitVtbl;

interface ICertExit {
    CONST_VTBL ICertExitVtbl* lpVtbl;
};

#ifdef COBJMACROS
/*** IUnknown methods ***/
#define ICertExit_QueryInterface(This,riid,ppvObject) \
    ((This)->lpVtbl->QueryInterface(This,riid,ppvObject))
#define ICertExit_AddRef(This) \
    ((This)->lpVtbl->AddRef(This))
#define ICertExit_Release(This) \
    ((This)->lpVtbl->Release(This))
/*** IDispatch methods ***/
#define ICertExit_GetTypeInfoCount(This,pctinfo) \
    ((This)->lpVtbl->GetTypeInfoCount(This,pctinfo))
#define ICertExit_GetTypeInfo(This,iTInfo,lcid,ppTInfo) \
    ((This)->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo))
#define ICertExit_GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId) \
    ((This)->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId))
#define ICertExit_Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr) \
    ((This)->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr))
/*** ICertExit methods ***/
#define ICertExit_Initialize(This,strConfig,pEventMask) \
    ((This)->lpVtbl->Initialize(This,strConfig,pEventMask))
#define ICertExit_Notify(This,ExitEvent,Context) \
    ((This)->lpVtbl->Notify(This,ExitEvent,Context))
#define ICertExit_GetDescription(This,pstrDescription) \
    ((This)->lpVtbl->GetDescription(This,pstrDescription))
#endif /* COBJMACROS */

#endif /* C */

#endif /* __ICertExit_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ICertExit2 interface
 */
#ifndef __ICertExit2_INTERFACE_DEFINED__
#define __ICertExit2_INTERFACE_DEFINED__

EXTERN_C const IID IID_ICertExit2;

#if defined(__cplusplus) && !defined(CINTERFACE)
#error no support for C++
#else /* C */
typedef struct ICertExit2Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ICertExit2 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ICertExit2 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ICertExit2 *This);

    /*** IDispatch methods ***/
    HRESULT (STDMETHODCALLTYPE *GetTypeInfoCount)(
        ICertExit2 *This,
        UINT *pctinfo);

    HRESULT (STDMETHODCALLTYPE *GetTypeInfo)(
        ICertExit2 *This,
        UINT iTInfo,
        LCID lcid,
        ITypeInfo **ppTInfo);

    HRESULT (STDMETHODCALLTYPE *GetIDsOfNames)(
        ICertExit2 *This,
        REFIID riid,
        LPOLESTR *rgszNames,
        UINT cNames,
        LCID lcid,
        DISPID *rgDispId);

    HRESULT (STDMETHODCALLTYPE *Invoke)(
        ICertExit2 *This,
        DISPID dispIdMember,
        REFIID riid,
        LCID lcid,
        WORD wFlags,
        DISPPARAMS *pDispParams,
        VARIANT *pVarResult,
        EXCEPINFO *pExcepInfo,
        UINT *puArgErr);

    /*** ICertExit methods ***/
    HRESULT (STDMETHODCALLTYPE *Initialize)(
        ICertExit2 *This,
        const BSTR strConfig,
        LONG *pEventMask);

    HRESULT (STDMETHODCALLTYPE *Notify)(
        ICertExit2 *This,
        LONG ExitEvent,
        LONG Context);

    HRESULT (STDMETHODCALLTYPE *GetDescription)(
        ICertExit2 *This,
        BSTR *pstrDescription);

    /*** ICertExit2 methods ***/
    HRESULT (STDMETHODCALLTYPE *GetManageModule)(
        ICertExit2 *This,
        ICertManageModule **ppManageModule);

    END_INTERFACE
} ICertExit2Vtbl;

interface ICertExit2 {
    CONST_VTBL ICertExit2Vtbl* lpVtbl;
};

#ifdef COBJMACROS
/*** IUnknown methods ***/
#define ICertExit2_QueryInterface(This,riid,ppvObject) \
    ((This)->lpVtbl->QueryInterface(This,riid,ppvObject))
#define ICertExit2_AddRef(This) \
    ((This)->lpVtbl->AddRef(This))
#define ICertExit2_Release(This) \
    ((This)->lpVtbl->Release(This))
/*** IDispatch methods ***/
#define ICertExit2_GetTypeInfoCount(This,pctinfo) \
    ((This)->lpVtbl->GetTypeInfoCount(This,pctinfo))
#define ICertExit2_GetTypeInfo(This,iTInfo,lcid,ppTInfo) \
    ((This)->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo))
#define ICertExit2_GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId) \
    ((This)->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId))
#define ICertExit2_Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr) \
    ((This)->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr))
/*** ICertExit methods ***/
#define ICertExit2_Initialize(This,strConfig,pEventMask) \
    ((This)->lpVtbl->Initialize(This,strConfig,pEventMask))
#define ICertExit2_Notify(This,ExitEvent,Context) \
    ((This)->lpVtbl->Notify(This,ExitEvent,Context))
#define ICertExit2_GetDescription(This,pstrDescription) \
    ((This)->lpVtbl->GetDescription(This,pstrDescription))
/*** ICertExit2 methods ***/
#define ICertExit2_GetManageModule(This,ppManageModule) \
    ((This)->lpVtbl->GetManageModule(This,ppManageModule))
#endif /* COBJMACROS */

#endif /* C */

#endif /* __ICertExit2_INTERFACE_DEFINED__ */

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) */

/* Begin additional prototypes for all interfaces */

ULONG __RPC_USER BSTR_UserSize(ULONG *, ULONG, BSTR *);
unsigned char * __RPC_USER BSTR_UserMarshal(ULONG *, unsigned char *, BSTR *);
unsigned char * __RPC_USER BSTR_UserUnmarshal(ULONG *, unsigned char *, BSTR *);
void __RPC_USER BSTR_UserFree(ULONG *, BSTR *);

/* End additional prototypes for all interfaces */

#endif /* __certexit_h__ */
