#include <apiset.h>
#include <apisetcconv.h>

#include <rpc.h>
#include <rpcndr.h>

#if (NTDDI_VERSION >= NTDDI_VISTA && !defined(_WIN32_WINNT))
#define _WIN32_WINNT 0x0600
#endif

#if (NTDDI_VERSION >= NTDDI_WS03 && !defined(_WIN32_WINNT))
#define _WIN32_WINNT 0x0502
#endif

#if (NTDDI_VERSION >= NTDDI_WINXP && !defined(_WIN32_WINNT))
#define _WIN32_WINNT 0x0501
#endif

#if (NTDDI_VERSION >= NTDDI_WIN2K && !defined(_WIN32_WINNT))
#define _WIN32_WINNT 0x0500
#endif

#ifndef _COMBASEAPI_H
#define _COMBASEAPI_H

/* Base Component Object Model defintions (Horror Show 6.0) */

#if __POCC__ >= 500
#pragma once
#endif

#include <pshpack8.h>

#define WINOLEAPI        EXTERN_C DECLSPEC_IMPORT HRESULT STDAPICALLTYPE
#define WINOLEAPI_(type) EXTERN_C DECLSPEC_IMPORT type STDAPICALLTYPE

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)

#define interface  struct

#define STDMETHOD(method)         HRESULT (STDMETHODCALLTYPE * method)
#define STDMETHOD_(type,method)   type (STDMETHODCALLTYPE * method)
#define STDMETHODV(method)        HRESULT (STDMETHODVCALLTYPE * method)
#define STDMETHODV_(type,method)  type (STDMETHODVCALLTYPE * method)

#define IFACEMETHOD(method)         STDMETHOD(method)
#define IFACEMETHOD_(type,method)   STDMETHOD_(type,method)
#define IFACEMETHODV(method)        STDMETHODV(method)
#define IFACEMETHODV_(type,method)  STDMETHODV_(type,method)

#ifndef BEGIN_INTERFACE
#define BEGIN_INTERFACE
#define END_INTERFACE
#endif /* !BEGIN_INTERFACE */

/* see basetyps.h (and then just give up) */
#define PURE
#define THIS_  INTERFACE *This,
#define THIS   INTERFACE *This
#ifdef CONST_VTABLE
#undef CONST_VTBL
#define CONST_VTBL const
#define DECLARE_INTERFACE(iface) \
    typedef interface iface { \
        const struct iface##Vtbl *lpVtbl; \
    } iface; \
    typedef const struct iface##Vtbl iface##Vtbl; \
    const struct iface##Vtbl
#else /* !CONST_VTABLE */
#undef CONST_VTBL
#define CONST_VTBL
#define DECLARE_INTERFACE(iface) \
    typedef interface iface { \
        struct iface##Vtbl *lpVtbl; \
    } iface; \
    typedef struct iface##Vtbl iface##Vtbl; \
    struct iface##Vtbl
#endif
#define DECLARE_INTERFACE_(iface, baseiface)  DECLARE_INTERFACE(iface)
#define DECLARE_INTERFACE_IID(iface, iid)               DECLARE_INTERFACE(iface)
#define DECLARE_INTERFACE_IID_(iface, baseiface, iid)   DECLARE_INTERFACE_(iface, baseiface)

#include <stdlib.h>

#define LISet32(li, v) ((li).HighPart = ((LONG) (v)) < 0 ? -1 : 0, (li).LowPart = (v))

#define ULISet32(li, v) ((li).HighPart = 0, (li).LowPart = (v))

#define CLSCTX_INPROC  (CLSCTX_INPROC_SERVER|CLSCTX_INPROC_HANDLER)
#if (_WIN32_WINNT >= 0x0400) || defined(_WIN32_DCOM)
#define CLSCTX_ALL     (CLSCTX_INPROC_SERVER|CLSCTX_INPROC_HANDLER|CLSCTX_LOCAL_SERVER|CLSCTX_REMOTE_SERVER)
#define CLSCTX_SERVER  (CLSCTX_INPROC_SERVER|CLSCTX_LOCAL_SERVER|CLSCTX_REMOTE_SERVER)
#else
#define CLSCTX_ALL     (CLSCTX_INPROC_SERVER|CLSCTX_INPROC_HANDLER|CLSCTX_LOCAL_SERVER)
#define CLSCTX_SERVER  (CLSCTX_INPROC_SERVER|CLSCTX_LOCAL_SERVER)
#endif

typedef enum tagREGCLS {
    REGCLS_SINGLEUSE = 0,
    REGCLS_MULTIPLEUSE = 1,
    REGCLS_MULTI_SEPARATE = 2,
    REGCLS_SUSPENDED = 4,
    REGCLS_SURROGATE = 8,
#if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
    REGCLS_AGILE = 0x10,
#endif /* (NTDDI_VERSION >= NTDDI_WINTHRESHOLD) */
} REGCLS;

typedef interface IRpcStubBuffer IRpcStubBuffer;
typedef interface IRpcChannelBuffer IRpcChannelBuffer;

typedef enum tagCOINITBASE {
#if (_WIN32_WINNT >= 0x0400) || defined(_WIN32_DCOM)
    COINITBASE_MULTITHREADED = 0x0,
#endif /* (_WIN32_WINNT >= 0x0400) || defined(_WIN32_DCOM) */
} COINITBASE;

#include <wtypesbase.h>
#include <unknwnbase.h>

#include <objidlbase.h>

#include <guiddef.h>

#ifndef INITGUID
#include <cguid.h>
#endif

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)
WINOLEAPI CoGetMalloc(DWORD dwMemContext, LPMALLOC *ppMalloc);
#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)
WINOLEAPI CreateStreamOnHGlobal(HGLOBAL hGlobal, BOOL fDeleteOnRelease, LPSTREAM *ppstm);
WINOLEAPI GetHGlobalFromStream(LPSTREAM pstm, HGLOBAL *phglobal);
WINOLEAPI_(void) CoUninitialize(void);
#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)
WINOLEAPI_(DWORD) CoGetCurrentProcess(void);
#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if (_WIN32_WINNT >= 0x0400) || defined(_WIN32_DCOM)

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)
WINOLEAPI CoInitializeEx(LPVOID pvReserved, DWORD dwCoInit);
#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)
WINOLEAPI CoGetCallerTID(LPDWORD lpdwTID);
#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)
WINOLEAPI CoGetCurrentLogicalThreadId(GUID *pguid);
#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM) */

#endif /* (_WIN32_WINNT >= 0x0400) || defined(_WIN32_DCOM) */

#if (_WIN32_WINNT >= 0x0501)

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)
WINOLEAPI CoGetContextToken(ULONG_PTR *pToken);
#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)
WINOLEAPI CoGetDefaultContext(APTTYPE aptType, REFIID riid, void **ppv);
#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#endif /* (_WIN32_WINNT >= 0x0501) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)

#if (NTDDI_VERSION >= NTDDI_WIN7)
WINOLEAPI CoGetApartmentType(APTTYPE *pAptType, APTTYPEQUALIFIER *pAptQualifier);
#endif /* (NTDDI_VERSION >= NTDDI_WIN7) */

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#if (NTDDI_VERSION >= NTDDI_WIN8)

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)

typedef struct tagServerInformation {
    DWORD dwServerPid;
    DWORD dwServerTid;
    UINT64 ui64ServerAddress;
} ServerInformation, *PServerInformation;

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)

WINOLEAPI CoDecodeProxy(
    DWORD dwClientPid,
    UINT64 ui64ProxyAddress,
    PServerInformation pServerInformation
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)
DECLARE_HANDLE(CO_MTA_USAGE_COOKIE);
WINOLEAPI CoIncrementMTAUsage(CO_MTA_USAGE_COOKIE *pCookie);
WINOLEAPI CoDecrementMTAUsage(CO_MTA_USAGE_COOKIE Cookie);
#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)

WINOLEAPI CoAllowUnmarshalerCLSID(REFCLSID clsid);

#if 1
  #if defined _M_IX86
    #define _CRT_INTERNAL_COMBASE_SYMBOL_PREFIX "_"
  #elif defined _M_X64 || defined _M_ARM || defined _M_ARM64
    #define _CRT_INTERNAL_COMBASE_SYMBOL_PREFIX ""
  #endif
  #ifdef _EXE_INITIALIZE_MTA
    #pragma comment(lib, "exe_initialize_mta")
    #pragma comment(linker, "/include:" _CRT_INTERNAL_COMBASE_SYMBOL_PREFIX "__PLEASE_LINK_WITH_exe_initialize_mta.lib")
  #endif /* _EXE_INITIALIZE_MTA */
#endif

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#endif /* (NTDDI_VERSION >= NTDDI_WIN8) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)
WINOLEAPI CoGetObjectContext(REFIID riid, LPVOID *ppv);
#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)
WINOLEAPI CoGetClassObject(
    REFCLSID rclsid,
    DWORD dwClsContext,
    LPVOID pvReserved,
    REFIID riid,
    LPVOID *ppv
);
#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)

WINOLEAPI CoRegisterClassObject(
    REFCLSID rclsid,
    LPUNKNOWN pUnk,
    DWORD dwClsContext,
    DWORD flags,
    LPDWORD lpdwRegister
);

WINOLEAPI CoRevokeClassObject(
    DWORD dwRegister
);

WINOLEAPI CoResumeClassObjects(void);

WINOLEAPI CoSuspendClassObjects(void);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)

WINOLEAPI_(ULONG) CoAddRefServerProcess(void);
WINOLEAPI_(ULONG) CoReleaseServerProcess(void);

WINOLEAPI CoGetPSClsid(
    REFIID riid,
    CLSID *pClsid
);

WINOLEAPI CoRegisterPSClsid(
    REFIID riid,
    REFCLSID rclsid
);

WINOLEAPI CoRegisterSurrogate(
    LPSURROGATE pSurrogate
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)

WINOLEAPI CoGetMarshalSizeMax(
    ULONG *pulSize,
    REFIID riid,
    LPUNKNOWN pUnk,
    DWORD dwDestContext,
    LPVOID pvDestContext,
    DWORD mshlflags
);

WINOLEAPI CoMarshalInterface(
    LPSTREAM pStm,
    REFIID riid,
    LPUNKNOWN pUnk,
    DWORD dwDestContext,
    LPVOID pvDestContext,
    DWORD mshlflags
);

WINOLEAPI CoUnmarshalInterface(
    LPSTREAM pStm,
    REFIID riid,
    LPVOID *ppv
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)

WINOLEAPI CoMarshalHresult(
    LPSTREAM pstm,
    HRESULT hresult
);

WINOLEAPI CoUnmarshalHresult(
    LPSTREAM pstm,
    HRESULT *phresult
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)

WINOLEAPI CoReleaseMarshalData(
    LPSTREAM pStm
);

WINOLEAPI CoDisconnectObject(
    LPUNKNOWN pUnk,
    DWORD dwReserved
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)

WINOLEAPI CoLockObjectExternal(
    LPUNKNOWN pUnk,
    BOOL fLock,
    BOOL fLastUnlockReleases
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)

WINOLEAPI CoGetStandardMarshal(
    REFIID riid,
    LPUNKNOWN pUnk,
    DWORD dwDestContext,
    LPVOID pvDestContext,
    DWORD mshlflags,
    LPMARSHAL *ppMarshal
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)

WINOLEAPI CoGetStdMarshalEx(
    LPUNKNOWN pUnkOuter,
    DWORD smexflags,
    LPUNKNOWN *ppUnkInner
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)

typedef enum tagSTDMSHLFLAGS {
    SMEXF_SERVER = 0x01,
    SMEXF_HANDLER = 0x02
} STDMSHLFLAGS;

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)
WINOLEAPI_(BOOL) CoIsHandlerConnected(LPUNKNOWN pUnk);
#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)

WINOLEAPI CoMarshalInterThreadInterfaceInStream(
    REFIID riid,
    LPUNKNOWN pUnk,
    LPSTREAM *ppStm
);

WINOLEAPI CoGetInterfaceAndReleaseStream(
    LPSTREAM pStm,
    REFIID iid,
    LPVOID *ppv
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)

WINOLEAPI CoCreateFreeThreadedMarshaler(
    LPUNKNOWN punkOuter,
    LPUNKNOWN *ppunkMarshal
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)

WINOLEAPI_(void) CoFreeUnusedLibraries(void);

#if (_WIN32_WINNT >= 0x0501)
WINOLEAPI_(void) CoFreeUnusedLibrariesEx(
    DWORD dwUnloadDelay,
    DWORD dwReserved
);
#endif /* (_WIN32_WINNT >= 0x0501) */

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)

#if (_WIN32_WINNT >= 0x0600)
WINOLEAPI CoDisconnectContext(DWORD dwTimeout);
#endif /* (_WIN32_WINNT >= 0x0600) */

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if (_WIN32_WINNT >= 0x0400) || defined(_WIN32_DCOM)

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)

WINOLEAPI CoInitializeSecurity(
    PSECURITY_DESCRIPTOR pSecDesc,
    LONG cAuthSvc,
    SOLE_AUTHENTICATION_SERVICE *asAuthSvc,
    void *pReserved1,
    DWORD dwAuthnLevel,
    DWORD dwImpLevel,
    void *pAuthList,
    DWORD dwCapabilities,
    void *pReserved3
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)

WINOLEAPI CoGetCallContext(
    REFIID riid,
    void **ppInterface
);

WINOLEAPI CoQueryProxyBlanket(
    IUnknown *pProxy,
    DWORD *pwAuthnSvc,
    DWORD *pAuthzSvc,
    LPOLESTR *pServerPrincName,
    DWORD *pAuthnLevel,
    DWORD *pImpLevel,
    RPC_AUTH_IDENTITY_HANDLE *pAuthInfo,
    DWORD *pCapabilites
);

WINOLEAPI CoSetProxyBlanket(
    IUnknown *pProxy,
    DWORD dwAuthnSvc,
    DWORD dwAuthzSvc,
    OLECHAR *pServerPrincName,
    DWORD dwAuthnLevel,
    DWORD dwImpLevel,
    RPC_AUTH_IDENTITY_HANDLE pAuthInfo,
    DWORD dwCapabilities
);

WINOLEAPI CoCopyProxy(
    IUnknown *pProxy,
    IUnknown **ppCopy
);

WINOLEAPI CoQueryClientBlanket(
    DWORD *pAuthnSvc,
    DWORD *pAuthzSvc,
    LPOLESTR *pServerPrincName,
    DWORD *pAuthnLevel,
    DWORD *pImpLevel,
    RPC_AUTHZ_HANDLE * pPrivs,
    DWORD *pCapabilities
);

WINOLEAPI CoImpersonateClient(void);

WINOLEAPI CoRevertToSelf(void);

WINOLEAPI CoQueryAuthenticationServices(
    DWORD *pcAuthSvc,
    SOLE_AUTHENTICATION_SERVICE **asAuthSvc
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)

WINOLEAPI CoSwitchCallContext(
    IUnknown *pNewObject,
    IUnknown **ppOldObject
);

#define COM_RIGHTS_EXECUTE 1
#define COM_RIGHTS_EXECUTE_LOCAL 2
#define COM_RIGHTS_EXECUTE_REMOTE 4
#define COM_RIGHTS_ACTIVATE_LOCAL 8
#define COM_RIGHTS_ACTIVATE_REMOTE 16
#define COM_RIGHTS_RESERVED1 32
#define COM_RIGHTS_RESERVED2 64

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM) */

#endif /* (_WIN32_WINNT >= 0x0400) || defined(_WIN32_DCOM) */

#if (WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES))

WINOLEAPI CoCreateInstance(
    REFCLSID rclsid,
    LPUNKNOWN pUnkOuter,
    DWORD dwClsContext,
    REFIID riid,
    LPVOID *ppv
);

#endif /* (WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)) */

#if (WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM))

#if (_WIN32_WINNT >= 0x0400) || defined(_WIN32_DCOM)
WINOLEAPI CoCreateInstanceEx(
    REFCLSID Clsid,
    IUnknown *punkOuter,
    DWORD dwClsCtx,
    COSERVERINFO *pServerInfo,
    DWORD dwCount,
    MULTI_QI *pResults
);
#endif /* (_WIN32_WINNT >= 0x0400) || defined(_WIN32_DCOM) */

#if (_WIN32_WINNT >= 0x0602)
WINOLEAPI CoCreateInstanceFromApp(
    REFCLSID Clsid,
    IUnknown *punkOuter,
    DWORD dwClsCtx,
    PVOID reserved,
    DWORD dwCount,
    MULTI_QI *pResults
);
#endif /* (_WIN32_WINNT >= 0x0602) */

#endif /* (WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)
WINOLEAPI CoRegisterActivationFilter(IActivationFilter *pActivationFilter);
#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if (_WIN32_WINNT >= 0x0500) || defined(_WIN32_DCOM)

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)

WINOLEAPI CoGetCancelObject(
    DWORD dwThreadId,
    REFIID iid,
    void **ppUnk
);

WINOLEAPI CoSetCancelObject(
    IUnknown *pUnk
);

WINOLEAPI CoCancelCall(
    DWORD dwThreadId,
    ULONG ulTimeout
);

WINOLEAPI CoTestCancel(void);

WINOLEAPI CoEnableCallCancellation(
    LPVOID pReserved
);

WINOLEAPI CoDisableCallCancellation(
    LPVOID pReserved
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#endif /* (_WIN32_WINNT >= 0x0500) || defined(_WIN32_DCOM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)

WINOLEAPI StringFromCLSID(
    REFCLSID rclsid,
    LPOLESTR *lplpsz
);

WINOLEAPI CLSIDFromString(
    LPCOLESTR lpsz,
    LPCLSID pclsid
);

WINOLEAPI StringFromIID(
    REFIID rclsid,
    LPOLESTR *lplpsz
);

WINOLEAPI IIDFromString(
    LPCOLESTR lpsz,
    LPIID lpiid
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)

WINOLEAPI ProgIDFromCLSID(
    REFCLSID clsid,
    LPOLESTR *lplpszProgID
);

WINOLEAPI CLSIDFromProgID(
    LPCOLESTR lpszProgID,
    LPCLSID lpclsid
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)

WINOLEAPI_(int) StringFromGUID2(
    REFGUID rguid,
    LPOLESTR lpsz,
    int cchMax
);

WINOLEAPI CoCreateGuid(
    GUID *pguid
);

typedef struct tagPROPVARIANT PROPVARIANT;

WINOLEAPI PropVariantCopy(
    PROPVARIANT *pvarDest,
    const PROPVARIANT *pvarSrc
);

WINOLEAPI PropVariantClear(
    PROPVARIANT *pvar
);

WINOLEAPI FreePropVariantArray(
    ULONG cVariants,
    PROPVARIANT *rgvars
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#if (_WIN32_WINNT >= 0x0400) || defined(_WIN32_DCOM)

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)

WINOLEAPI CoWaitForMultipleHandles(
    DWORD dwFlags,
    DWORD dwTimeout,
    ULONG cHandles,
    LPHANDLE pHandles,
    LPDWORD lpdwindex
);

/* Flags for Synchronization API and Classes */

typedef enum tagCOWAIT_FLAGS {
    COWAIT_DEFAULT = 0,
    COWAIT_WAITALL = 1,
    COWAIT_ALERTABLE = 2,
    COWAIT_INPUTAVAILABLE = 4,
    COWAIT_DISPATCH_CALLS = 8,
    COWAIT_DISPATCH_WINDOW_MESSAGES = 0x10,
} COWAIT_FLAGS;

#if (NTDDI_VERSION >= NTDDI_WIN8)

typedef enum CWMO_FLAGS {
    CWMO_DEFAULT = 0,
    CWMO_DISPATCH_CALLS = 1,
    CWMO_DISPATCH_WINDOW_MESSAGES = 2,
} CWMO_FLAGS;

WINOLEAPI CoWaitForMultipleObjects(
    DWORD dwFlags,
    DWORD dwTimeout,
    ULONG cHandles,
    const HANDLE *pHandles,
    LPDWORD lpdwindex
);

#endif /* (NTDDI_VERSION >= NTDDI_WIN8) */

#define CWMO_MAX_HANDLES  56

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#endif /* (_WIN32_WINNT >= 0x0400) || defined(_WIN32_DCOM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)

WINOLEAPI CoGetTreatAsClass(
    REFCLSID clsidOld,
    LPCLSID pClsidNew
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)

#if (_WIN32_WINNT >= 0x0501)
WINOLEAPI CoInvalidateRemoteMachineBindings(
    LPOLESTR pszMachineName
);
#endif /* (_WIN32_WINNT >= 0x0501) */

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)

#if (NTDDI_VERSION >= NTDDI_WINBLUE)

enum AgileReferenceOptions {
    AGILEREFERENCE_DEFAULT = 0,
    AGILEREFERENCE_DELAYEDMARSHAL = 1,
};

WINOLEAPI RoGetAgileReference(
    enum AgileReferenceOptions options,
    REFIID riid,
    IUnknown *pUnk,
    IAgileReference **ppAgileReference
);

#endif /* (NTDDI_VERSION >= NTDDI_WINBLUE) */

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)

typedef HRESULT (STDAPICALLTYPE *LPFNGETCLASSOBJECT)(REFCLSID, REFIID, LPVOID *);
typedef HRESULT (STDAPICALLTYPE *LPFNCANUNLOADNOW)(void);

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID *ppv);
STDAPI DllCanUnloadNow(void);

WINOLEAPI_(LPVOID)CoTaskMemAlloc(SIZE_T cb);
WINOLEAPI_(LPVOID)CoTaskMemRealloc(LPVOID pv, SIZE_T cb);
WINOLEAPI_(void)CoTaskMemFree(LPVOID pv);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)

WINOLEAPI CoFileTimeNow(FILETIME *lpFileTime);

WINOLEAPI CLSIDFromProgIDEx(
    LPCOLESTR lpszProgID,
    LPCLSID lpclsid
);

#if (NTDDI_VERSION >= NTDDI_WIN10_VB)

#if !defined(_CO_DEVICE_CATALOG_)
#define _CO_DEVICE_CATALOG_
#endif

DECLARE_HANDLE(CO_DEVICE_CATALOG_COOKIE);

WINOLEAPI CoRegisterDeviceCatalog(
    PCWSTR deviceInstanceId,
    CO_DEVICE_CATALOG_COOKIE *cookie
);

WINOLEAPI CoRevokeDeviceCatalog(
    CO_DEVICE_CATALOG_COOKIE cookie
);

#endif /* (NTDDI_VERSION >= NTDDI_WIN10_VB) */

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#include <poppack.h>

#endif /* _COMBASEAPI_H */
