#ifndef _FIBERSAPI_H
#define _FIBERSAPI_H

#if __POCC__ >= 500
#pragma once
#endif

/* ApiSet contract for api-ms-win-core-fibers-l1 */

#include <apiset.h>
#include <apisetcconv.h>
#include <minwindef.h>

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)

#if (_WIN32_WINNT >= 0x0600)

#ifndef FLS_OUT_OF_INDEXES
#define FLS_OUT_OF_INDEXES  ((DWORD)0xFFFFFFFF)
#endif /* FLS_OUT_OF_INDEXES */

WINBASEAPI DWORD WINAPI FlsAlloc(
    PFLS_CALLBACK_FUNCTION lpCallback);

WINBASEAPI PVOID WINAPI FlsGetValue(
    DWORD dwFlsIndex);

WINBASEAPI BOOL WINAPI FlsSetValue(
    DWORD dwFlsIndex,
    PVOID lpFlsData);

WINBASEAPI BOOL WINAPI FlsFree(
    DWORD dwFlsIndex);

#endif /* (_WIN32_WINNT >= 0x0600) */

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)

#if (_WIN32_WINNT >= 0x0600)

WINBASEAPI BOOL WINAPI IsThreadAFiber(VOID);

#endif /* (_WIN32_WINNT >= 0x0600) */

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#endif /* _FIBERSAPI_H */
