#ifndef _ICMPAPI_H
#define _ICMPAPI_H

#if __POCC__ >= 500
#pragma once
#endif

/* Windows ICMP Echo Request API definitions (idiot version) */

#include <winapifamily.h>

#ifndef IPHLPAPI_DLL_LINKAGE
#ifdef DECLSPEC_IMPORT
#define IPHLPAPI_DLL_LINKAGE DECLSPEC_IMPORT
#else
#define IPHLPAPI_DLL_LINKAGE
#endif
#endif

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)

IPHLPAPI_DLL_LINKAGE HANDLE WINAPI IcmpCreateFile(
    void
);

#if (NTDDI_VERSION >= NTDDI_WINXP)
IPHLPAPI_DLL_LINKAGE HANDLE WINAPI Icmp6CreateFile(
    void
);
#endif /* (NTDDI_VERSION >= NTDDI_WINXP) */

IPHLPAPI_DLL_LINKAGE BOOL WINAPI IcmpCloseHandle(
    HANDLE IcmpHandle
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)

IPHLPAPI_DLL_LINKAGE DWORD WINAPI IcmpSendEcho(
    HANDLE IcmpHandle,
    IPAddr DestinationAddress,
    LPVOID RequestData,
    WORD RequestSize,
    PIP_OPTION_INFORMATION RequestOptions,
    LPVOID ReplyBuffer,
    DWORD ReplySize,
    DWORD Timeout
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)

IPHLPAPI_DLL_LINKAGE DWORD WINAPI IcmpSendEcho2(
    HANDLE IcmpHandle,
    HANDLE Event,
#ifdef PIO_APC_ROUTINE_DEFINED
    PIO_APC_ROUTINE ApcRoutine,
#else /* !PIO_APC_ROUTINE_DEFINED */
    FARPROC ApcRoutine,
#endif /* !PIO_APC_ROUTINE_DEFINED */
    PVOID ApcContext,
    IPAddr DestinationAddress,
    LPVOID RequestData,
    WORD RequestSize,
    PIP_OPTION_INFORMATION RequestOptions,
    LPVOID ReplyBuffer,
    DWORD ReplySize,
    DWORD Timeout
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)

#if (NTDDI_VERSION >= NTDDI_VISTASP1)
IPHLPAPI_DLL_LINKAGE DWORD WINAPI IcmpSendEcho2Ex(
    HANDLE IcmpHandle,
    HANDLE Event,
#ifdef PIO_APC_ROUTINE_DEFINED
    PIO_APC_ROUTINE ApcRoutine,
#else /* !PIO_APC_ROUTINE_DEFINED */
    FARPROC ApcRoutine,
#endif /* !PIO_APC_ROUTINE_DEFINED */
    PVOID ApcContext,
    IPAddr SourceAddress,
    IPAddr DestinationAddress,
    LPVOID RequestData,
    WORD RequestSize,
    PIP_OPTION_INFORMATION RequestOptions,
    LPVOID ReplyBuffer,
    DWORD ReplySize,
    DWORD Timeout
);
#endif /* (NTDDI_VERSION >= NTDDI_VISTASP1) */

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)

#if (NTDDI_VERSION >= NTDDI_WINXP)
IPHLPAPI_DLL_LINKAGE DWORD WINAPI Icmp6SendEcho2(
    HANDLE IcmpHandle,
    HANDLE Event,
#ifdef PIO_APC_ROUTINE_DEFINED
    PIO_APC_ROUTINE ApcRoutine,
#else /* !PIO_APC_ROUTINE_DEFINED */
    FARPROC ApcRoutine,
#endif /* !PIO_APC_ROUTINE_DEFINED */
    PVOID ApcContext,
    struct sockaddr_in6 *SourceAddress,
    struct sockaddr_in6 *DestinationAddress,
    LPVOID RequestData,
    WORD RequestSize,
    PIP_OPTION_INFORMATION RequestOptions,
    LPVOID ReplyBuffer,
    DWORD ReplySize,
    DWORD Timeout
);
#endif /* (NTDDI_VERSION >= NTDDI_WINXP) */

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)

IPHLPAPI_DLL_LINKAGE DWORD WINAPI IcmpParseReplies(
    LPVOID ReplyBuffer,
    DWORD ReplySize
);

#if (NTDDI_VERSION >= NTDDI_WINXP)
IPHLPAPI_DLL_LINKAGE DWORD WINAPI Icmp6ParseReplies(
    LPVOID ReplyBuffer,
    DWORD ReplySize
);
#endif /* (NTDDI_VERSION >= NTDDI_WINXP) */

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM) */

#endif /* _ICMPAPI_H */
