#ifndef _LMAPIBUF_H
#define _LMAPIBUF_H

#if __POCC__ >= 500
#pragma once
#endif

/* NetApiBuffer API definitions */

#include <winapifamily.h>

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)

NET_API_STATUS NET_API_FUNCTION NetApiBufferAllocate(
    DWORD ByteCount,
    LPVOID * Buffer);

NET_API_STATUS NET_API_FUNCTION NetApiBufferFree (
    LPVOID Buffer);

NET_API_STATUS NET_API_FUNCTION NetApiBufferReallocate(
    LPVOID OldBuffer,
    DWORD NewByteCount,
    LPVOID *NewBuffer);

NET_API_STATUS NET_API_FUNCTION NetApiBufferSize(
    LPVOID Buffer,
    LPDWORD ByteCount);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)

NET_API_STATUS NET_API_FUNCTION NetapipBufferAllocate (
    DWORD ByteCount,
    LPVOID *Buffer);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_APP)

NET_API_STATUS NET_API_FUNCTION NetApiBufferFree (
    LPVOID Buffer);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_APP) */

#endif /* _LMAPIBUF_H */
