#ifndef _UTILAPISET_H
#define _UTILAPISET_H

#if __POCC__ >= 500
#pragma once
#endif

/* ApiSet contract for api-ms-win-core-util-l1-1-0 */

#include <apiset.h>
#include <apisetcconv.h>
#include <minwindef.h>

#include <winapifamily.h>

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)

WINBASEAPI PVOID WINAPI EncodePointer(PVOID Ptr);
WINBASEAPI PVOID WINAPI DecodePointer(PVOID Ptr);
WINBASEAPI PVOID WINAPI EncodeSystemPointer(PVOID Ptr);
WINBASEAPI PVOID WINAPI DecodeSystemPointer(PVOID Ptr);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM)

WINBASEAPI HRESULT WINAPI EncodeRemotePointer(
    HANDLE ProcessHandle,
    PVOID Ptr,
    PVOID *EncodedPtr
);

WINBASEAPI HRESULT WINAPI DecodeRemotePointer(
    HANDLE ProcessHandle,
    PVOID Ptr,
    PVOID *DecodedPtr
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_PC_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES)

WINBASEAPI BOOL WINAPI Beep(
    DWORD dwFreq,
    DWORD dwDuration
);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_PC_APP | WINAPI_PARTITION_SYSTEM | WINAPI_PARTITION_GAMES) */

#endif /* _UTILAPISET_H */
