#ifndef _WOWNT32_H
#define _WOWNT32_H

#if __POCC__ >= 500
#pragma once
#endif

/* Windows on Windows (WOW) 32-bit thunking definitions */

#include <winapifamily.h>

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)

typedef LPVOID (WINAPI *PFNWOWGETVDMPOINTER)(
    DWORD vp,
    DWORD dwBytes,
    BOOL fProtectedMode
);

LPVOID WINAPI WOWGetVDMPointer(
    DWORD vp,
    DWORD dwBytes,
    BOOL fProtectedMode
);

LPVOID WINAPI WOWGetVDMPointerFix(
    DWORD vp,
    DWORD dwBytes,
    BOOL fProtectedMode
);

VOID WINAPI WOWGetVDMPointerUnfix(
    DWORD vp
);

typedef WORD (WINAPI *PFNWOWGLOBALFREE16)(WORD hMem);
typedef DWORD (WINAPI *PFNWOWGLOBALLOCK16)(WORD hMem);
typedef BOOL (WINAPI *PFNWOWGLOBALUNLOCK16)(WORD hMem);

WORD WINAPI WOWGlobalAlloc16(WORD wFlags, DWORD cb);
WORD WINAPI WOWGlobalFree16(WORD hMem);
DWORD WINAPI WOWGlobalLock16(WORD hMem);
BOOL WINAPI WOWGlobalUnlock16(WORD hMem);

typedef DWORD (WINAPI *PFNWOWGLOBALALLOCLOCK16)(WORD wFlag, DWORD cb, WORD *phMem);
typedef WORD (WINAPI *PFNWOWGLBALUNLOCKFREE16)(DWORD vpMem);
typedef DWORD (WINAPI *PFNWOWGLOBALLOCKSIZE16)(WORD hMem, PDWORD pcb);

DWORD WINAPI WOWGlobalAllocLock16(WORD wFlags, DWORD cb, WORD *phMem);
WORD WINAPI WOWGlobalUnlockFree16(DWORD vpMem);
DWORD WINAPI WOWGlobalLockSize16(WORD hMem, PDWORD pcb);

typedef VOID (WINAPI *PFNWOWYIELD16)(VOID);
typedef VOID (WINAPI *PFNWOWDIRECTEDYIELD16)(WORD htask16);

VOID WINAPI WOWYield16(VOID);
VOID WINAPI WOWDirectedYield16(WORD htask16);

typedef enum _WOW_HANDLE_TYPE { /* WOW */
    WOW_TYPE_HWND,
    WOW_TYPE_HMENU,
    WOW_TYPE_HDWP,
    WOW_TYPE_HDROP,
    WOW_TYPE_HDC,
    WOW_TYPE_HFONT,
    WOW_TYPE_HMETAFILE,
    WOW_TYPE_HRGN,
    WOW_TYPE_HBITMAP,
    WOW_TYPE_HBRUSH,
    WOW_TYPE_HPALETTE,
    WOW_TYPE_HPEN,
    WOW_TYPE_HACCEL,
    WOW_TYPE_HTASK,
    WOW_TYPE_FULLHWND
} WOW_HANDLE_TYPE;

typedef HANDLE (WINAPI *PFNWOWHANDLE32)(WORD, WOW_HANDLE_TYPE);
typedef WORD (WINAPI *PFNWOWHANDLE16)(HANDLE, WOW_HANDLE_TYPE);

HANDLE WINAPI WOWHandle32(WORD, WOW_HANDLE_TYPE);
WORD WINAPI WOWHandle16(HANDLE, WOW_HANDLE_TYPE);

#ifndef REGISTERED_WOW_HANDLERS
#define WOWHANDLE32  WOWHandle32
#define WOWHANDLE16  WOWHandle16
#else
#define WOWHANDLE32  REGISTERED_WOW_HANDLERS.pfnWOWHandle32
#define WOWHANDLE16  REGISTERED_WOW_HANDLERS.pfnWOWHandle16
#endif

#define HWND_32(h16)      ((HWND)       (WOWHANDLE32(h16, WOW_TYPE_HWND)))
#define HMENU_32(h16)     ((HMENU)      (WOWHANDLE32(h16, WOW_TYPE_HMENU)))
#define HDWP_32(h16)      ((HDWP)       (WOWHANDLE32(h16, WOW_TYPE_HDWP)))
#define HDROP_32(h16)     ((HDROP)      (WOWHANDLE32(h16, WOW_TYPE_HDROP)))
#define HDC_32(h16)       ((HDC)        (WOWHANDLE32(h16, WOW_TYPE_HDC)))
#define HFONT_32(h16)     ((HFONT)      (WOWHANDLE32(h16, WOW_TYPE_HFONT)))
#define HMETAFILE_32(h16) ((HMETAFILE)  (WOWHANDLE32(h16, WOW_TYPE_HMETAFILE)))
#define HRGN_32(h16)      ((HRGN)       (WOWHANDLE32(h16, WOW_TYPE_HRGN)))
#define HBITMAP_32(h16)   ((HBITMAP)    (WOWHANDLE32(h16, WOW_TYPE_HBITMAP)))
#define HBRUSH_32(h16)    ((HBRUSH)     (WOWHANDLE32(h16, WOW_TYPE_HBRUSH)))
#define HPALETTE_32(h16)  ((HPALETTE)   (WOWHANDLE32(h16, WOW_TYPE_HPALETTE)))
#define HPEN_32(h16)      ((HPEN)       (WOWHANDLE32(h16, WOW_TYPE_HPEN)))
#define HACCEL_32(h16)   ((HACCEL)      (WOWHANDLE32(h16, WOW_TYPE_HACCEL)))
#define HTASK_32(h16)   ((DWORD)        (WOWHANDLE32(h16, WOW_TYPE_HTASK)))
#define FULLHWND_32(h16)  ((HWND)       (WOWHANDLE32(h16, WOW_TYPE_FULLHWND)))

#define HWND_16(h32)        (WOWHANDLE16(h32, WOW_TYPE_HWND))
#define HMENU_16(h32)       (WOWHANDLE16(h32, WOW_TYPE_HMENU))
#define HDWP_16(h32)        (WOWHANDLE16(h32, WOW_TYPE_HDWP))
#define HDROP_16(h32)       (WOWHANDLE16(h32, WOW_TYPE_HDROP))
#define HDC_16(h32)         (WOWHANDLE16(h32, WOW_TYPE_HDC))
#define HFONT_16(h32)       (WOWHANDLE16(h32, WOW_TYPE_HFONT))
#define HMETAFILE_16(h32)   (WOWHANDLE16(h32, WOW_TYPE_HMETAFILE))
#define HRGN_16(h32)        (WOWHANDLE16(h32, WOW_TYPE_HRGN))
#define HBITMAP_16(h32)     (WOWHANDLE16(h32, WOW_TYPE_HBITMAP))
#define HBRUSH_16(h32)      (WOWHANDLE16(h32, WOW_TYPE_HBRUSH))
#define HPALETTE_16(h32)    (WOWHANDLE16(h32, WOW_TYPE_HPALETTE))
#define HPEN_16(h32)        (WOWHANDLE16(h32, WOW_TYPE_HPEN))
#define HACCEL_16(h32)      (WOWHANDLE16(h32, WOW_TYPE_HACCEL))
#define HTASK_16(h32)       (WOWHANDLE16(h32, WOW_TYPE_HTASK))

typedef DWORD (WINAPI *PFNWOWCALLBACK16)(
    DWORD vpfn16,
    DWORD dwParam
);

typedef BOOL (WINAPI *PFNWOWCALLBACK16EX)(
    DWORD vpfn16,
    DWORD dwFlags,
    DWORD cbArgs,
    PVOID pArgs,
    PDWORD pdwRetCode
);

DWORD WINAPI WOWCallback16(DWORD vpfn16, DWORD dwParam);

#define WCB16_MAX_CBARGS  (16)

#define WCB16_PASCAL  (0x0)
#define WCB16_CDECL   (0x1)

BOOL WINAPI WOWCallback16Ex(
    DWORD vpfn16,
    DWORD dwFlags,
    DWORD cbArgs,
    PVOID pArgs,
    PDWORD pdwRetCode
);

typedef BOOL (WINAPI *PFNWOWFREEMETAFILE)(HANDLE h32);
BOOL WINAPI WOWFreeMetafile(HANDLE h32);

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) */

#endif /* _WOWNT32_H */
