#ifndef _XMLDSODID_H
#define _XMLDSODID_H

#include <winapifamily.h>

#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)

#define  DISPID_XMLDSO                      0x00010000
#define  DISPID_XMLDSO_DOCUMENT             DISPID_XMLDSO  +  1
#define  DISPID_XMLDSO_JAVADSOCOMPATIBLE    DISPID_XMLDSO_DOCUMENT  +  1

#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) */

#endif /* _XMLDSODID_H */
