// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define DLG_MAIN  1001
#define IDR_ICO_MAIN  8001
#define DID_REDBUTTON  4001
#define DID_BLUEBUTTON  4002
#define DID_REDLABEL  4003
#define DID_BLUELABEL  4004
