// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define DLG_MAIN  1001
#define IDR_ICO_MAIN  8001
#define IDB_EXIT  1
#define IDC_SYNC  4009
#define IDB_SELLONG  4010
#define IDB_SELSHORT  4011
#define IDB_SELTIME  4012
#define IDB_SETBIRTH  4013
#define IDB_SELHAND  4014
#define IDB_SETHAND  4015
#define IDDT_LONG  4020
#define IDDT_SHORT  4030
#define IDDT_TIME  4003
