// INCLUDE FILE generated by "Pelles C for Windows, version 4.00".

#ifndef _DLLSHARE_H
#define _DLLSHARE_H

#ifdef _DLLSHARE_
#define DLLSHAREAPI  __declspec(dllexport)
#else
#define DLLSHAREAPI  __declspec(dllimport)
#endif /* _DLLSHARE_ */

#ifndef WINAPI
#define WINAPI  __stdcall
#endif

DLLSHAREAPI void WINAPI set_shared_int_value(int new_shared_int);
DLLSHAREAPI int WINAPI get_shared_int_value(void);
DLLSHAREAPI void WINAPI set_private_int_value(int new_private_int);
DLLSHAREAPI int WINAPI get_private_int_value(void);

#endif /* _DLLSHARE_H */
