// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define DLG_MAIN  1001
#define IDR_ICO_MAIN  8001
#define IDOK  1


#define DID_SHARED_VALUE  4001
#define IDSETSHARED  4002
#define DID_PRIVATE_VALUE  4003
#define IDSETPRIVATE  4004
