// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define DLG_ABOUT  1001
#define IDR_MNU_MAIN  2001
#define IDM_ABOUT  6001
#define IDR_ICO_MAIN  8001
#define IDM_NEWWINDOW  6002
#define IDM_EXIT  6003
#define DLG_MDICHILD  1002




#define DID_SAMPLE1  4004
#define DID_SAMPLE2  4005
#define DID_OPTION1  4001
#define DID_OPTION2  4002
#define DID_OPTION3  4003
