// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define DLG_MAIN	1001
#define IDR_ICO_MAIN	8001
#define DLG_STYLES	1002
#define IDSTYOK		4002

#define FGCOLOR		4003

#define GDCOLOR		4009
#define BDCOLOR		4010
#define STYSPEED	4015
#define BGCOLOR		4008
#define COLOR1		4007
#define COLOR2		4016
#define COMBO1		4004
#define COMBO2		4019
#define LBL1		5001
#define LBL2		5002
#define CKPEAK		4021
#define CKFILL		4013
#define LBGDSZ		4011
#define EDGDSZ		4012
#define IDABOUT  4014
