// INCLUDE FILE generated by "Pelles C for Windows, version 2.73".

#ifndef _TESTDLL1_H
#define _TESTDLL1_H

#ifdef _TESTDLL1_
#define TESTDLL1API  __declspec(dllexport)
#else
#define TESTDLL1API  __declspec(dllimport)
#endif /* _TESTDLL1_ */

#ifndef WINAPI
#define WINAPI  __stdcall
#endif

TESTDLL1API int WINAPI SampleDllFunction1(void);

#endif /* _TESTDLL1_H */
