// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

extern HANDLE ghInstance;

#define TOUPPER(ch)  CharUpper((LPTSTR)(TCHAR)(ch))
#define NELEMS(a)  (sizeof(a) / sizeof(a[0]))

#define LoadIconSm(hinst,pname)  LoadImage((hinst), (pname), IMAGE_ICON, 16, 16, LR_DEFAULTCOLOR|LR_SHARED)

#define IDR_ICO_CHECK  8002

#define DLG_ABOUT  1001
#define IDR_MNU_MAIN  2001
#define IDR_ICO_MAIN  8001
#define IDR_BMP_MAINTOOLS  8003
#define IDM_FILE_NEW  6002
#define IDM_FILE_OPEN  6003
#define IDM_FILE_SAVE  6004
#define IDM_FILE_SAVEAS  6005
#define IDM_FILE_EXIT  6006
#define IDM_HELP_ABOUT  6001
