// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define DLG_MAIN  1001
#define IDR_ICO_MAIN  8001

#define DID_FIREWALL_HEALTH  4002
#define DID_ANTIVIRUS_HEALTH  4004
#define DID_ANTI_SPYWARE_HEALTH  4005
