// INCLUDE FILE generated by "Pelles C for Windows, version 2.73".

#ifndef _TESTDLL2_H
#define _TESTDLL2_H

#ifdef _TESTDLL2_
#define TESTDLL2API  __declspec(dllexport)
#else
#define TESTDLL2API  __declspec(dllimport)
#endif /* _TESTDLL2_ */

#ifndef WINAPI
#define WINAPI  __stdcall
#endif

TESTDLL2API int WINAPI SampleDllFunction2(void);

#endif /* _TESTDLL2_H */
