#define BabyGrid_ProtectCell(hGrid,pCell,fSet) (int)SendMessage((hGrid),BGM_PROTECTCELL,(UINT)(pCell),fSet)
#define BabyGrid_SetProtect(hGrid,fSet) (int)SendMessage((hGrid),BGM_SETPROTECT,fSet,0L)
#define BabyGrid_SetCellData(hGrid,pCell,lpzText) (int)SendMessage((hGrid),BGM_SETCELLDATA,(UINT)(pCell),(long)(lpzText))
#define BabyGrid_GetCellData(hGrid,pCell,lpzText) (int)SendMessage((hGrid),BGM_GETCELLDATA,(UINT)(pCell),(long)(lpzText))
#define BabyGrid_ClearGrid(hGrid) (int)SendMessage((hGrid),BGM_CLEARGRID,0L,0L)
#define BabyGrid_SetGridDim(hGrid,nRows,nCols) (int)SendMessage((hGrid),BGM_SETGRIDDIM,nRows,nCols)
#define BabyGrid_DeleteCell(hGrid,pCell) (int)SendMessage((hGrid),BGM_DELETECELL,(pCell),0L)
#define BabyGrid_SetCursorPos(hGrid,iRow,iCol) (int)SendMessage((hGrid),BGM_SETCURSORPOS,iRow,iCol)
#define BabyGrid_AutoRow(hGrid,fSet) (int)SendMessage((hGrid),BGM_AUTOROW,fSet,0L)
#define BabyGrid_GetOwnerDrawItem(hGrid) (int)SendMessage((hGrid),BGM_GETOWNERDRAWITEM,0L,0L)
#define BabyGrid_SetColWidth(hGrid,iCol,nWidth) (int)SendMessage((hGrid),BGM_SETCOLWIDTH,iCol,nWidth)
#define BabyGrid_SetHeaderRowHeight(hGrid,nHeight) (int)SendMessage((hGrid),BGM_SETHEADERROWHEIGHT,nHeight,0L)
#define BabyGrid_GetType(hGrid,pCell) (int)SendMessage((hGrid),BGM_GETTYPE,(UINT)(pCell),0L)
#define BabyGrid_GetProtection(hGrid,pCell) (BOOL)SendMessage((hGrid),BGM_GETPROTECTION,(PcELL),0L) 

#define BabyGrid_DrawCursor(hGrid,iSelfIndex) (int)SendMessage((hGrid),BGM_DRAWCURSOR,iSelfIndex,0L)

#define BabyGrid_SetRowHeight(hGrid,iHeight) (int)SendMessage((hGrid),BGM_SETROWHEIGHT,iHeight,0L)
#define BabyGrid_SetCursorColor(hGrid, clrCrsr) (int)SendMessage((hGrid),BGM_SETCURSORCOLOR,(UINT)clrCrsr,0L)
#define BabyGrid_SetProtectColor(hGrid, clrProtect) (int)SendMessage((hGrid),BGM_SETPROTECTCOLOR,(UINT) clrProtect,0L)
#define BabyGrid_SetUnprotectColor(hGrid, clrUProtect) (int)SendMessage((hGrid),BGM_SETUNPROTECTCOLOR,(UINT) clrUProtect,0L)
#define BabyGrid_SetRowsNumbered(hGrid,fSet) (int)SendMessage((hGrid),BGM_SETROWSNUMBERED,fSet,0L)
#define BabyGrid_SetColsNumbered(hGrid,fSet) (int)SendMessage((hGrid),BGM_SETCOLSNUMBERED,fSet,0L)
#define BabyGrid_ShowHilight(hGrid,fShow) (int)SendMessage((hGrid),BGM_SHOWHILIGHT,fShow,0L)
#define BabyGrid_GetRows(hGrid) (int)SendMessage((hGrid),BGM_GETROWS,0L,0L)
#define BabyGrid_GetCols(hGrid) (int)SendMessage((hGrid),BGM_GETCOLS,0L,0L)
#define BabyGrid_NotifyRowChanged(hGrid) (int)SendMessage((hGrid),BGM_NOTIFYROWCHANGED,0L,0L)
#define BabyGrid_NotifyColChanged(hGrid) (int)SendMessage((hGrid),BGM_NOTIFYCOLCHANGED,0L,0L)
#define BabyGrid_GetRow(hGrid) (int)SendMessage((hGrid),BGM_GETROW,0L,0L)
#define BabyGrid_GetCol(hGrid) (int)SendMessage((hGrid),BGM_GETCOL,0L,0L)
#define BabyGrid_PaintGrid(hGrid) (int)SendMessage((hGrid),BGM_PAINTGRID,0L,0L)
#define BabyGrid_GetColWidth(hGrid,iCol) (int)SendMessage((hGrid),BGM_GETCOLWIDTH,iCol,0L)
#define BabyGrid_GetRowHeight(hGrid) (int)SendMessage((hGrid),BGM_GETROWHEIGHT,0L,0L) 
#define BabyGrid_GetHeaderRowHeight(hGrid) (int)SendMessage((hGrid),BGM_GETHEADERROWHEIGHT,0L,0L)
#define BabyGrid_SetTitleHeight(hGrid,iHeight) (int)SendMessage((hGrid),BGM_SETTITLEHEIGHT,iHeight,0L)
#define BabyGrid_SetHilightColor(hGrid, clrHilt) (int)SendMessage((hGrid),BGM_SETHILIGHTCOLOR,(UINT)clrHilt,0L)
#define BabyGrid_SetHilightTextColor(hGrid, clrHlText) (int)SendMessage((hGrid),BGM_SETHILIGHTTEXTCOLOR,(UINT)clrHlText,0L)
#define BabyGrid_SetEditable(hGrid,fSet) (int)SendMessage((hGrid),BGM_SETEDITABLE,fSet,0L)
#define BabyGrid_SetGridLineColor(hGrid,clrGrdLine)  (int)SendMessage((hGrid),BGM_SETGRIDLINECOLOR,(UINT)clrGrdLine,0L)
#define BabyGrid_ExtendLastColumn(hGrid,fSet) (int)SendMessage((hGrid),BGM_EXTENDLASTCOLUMN,fSet,0L)
#define BabyGrid_ShowIntegralRows(hGrid,fShow) (int)SendMessage((hGrid),BGM_SHOWINTEGRALROWS,fShow,0L)
#define BabyGrid_SetEllipsis(hGrid,fSet) (int)SendMessage((hGrid),BGM_SETELLIPSIS,fSet,0L)
#define BabyGrid_SetColAutoWidth(hGrid,fSet) (int)SendMessage((hGrid),BGM_SETCOLAUTOWIDTH,fSet,0L)
#define BabyGrid_SetAllowColResize (hGrid,fColRsz) (int)SendMessage((hGrid),BGM_SETALLOWCOLRESIZE,fColRsz,0L)
#define BabyGrid_SetTitleFont(hGrid,hFont) (int)SendMessage((hGrid),BGM_SETTITLEFONT,(hFont),0L)
#define BabyGrid_SetHeadingFont(hGrid,hFont) (int)SendMessage((hGrid),BGM_SETHEADINGFONT,(hFont),0L)


