// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define IDM_MAIN_MENU  2001
#define IDR_ACCELS  3001
#define IDM_EXIT  6001
#define IDM_LARGE_ICONS  6002
#define IDM_SMALL_ICONS  6003
#define IDM_LIST  6004
#define IDM_REFRESH  6005
#define IDC_SPLIT_CURSOR  8001
